// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://anbmihxzbhkizcynrgvs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFuYm1paHh6YmhraXpjeW5yZ3ZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDc3NTEsImV4cCI6MjA3MTg4Mzc1MX0.XwNgMVwAm5C7f_B-zlqwoLz97lZVzNc3g6f2fDtiJT4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});